Repository microsoft/Microsoft.IO.RecyclableMemoryStream, pull requests merged in 2023-02, with the labels that each got.

#261 Move blocks list allocation to constructor
  src/RecyclableMemoryStream.cs
Labels: bug

#265 Change when pool stats are reported
  UnitTests/Tests.cs
  src/RecyclableMemoryStream.cs
  src/RecyclableMemoryStreamManager.cs
Labels: enhancement

#264 Update some events to Warning, add more data
  src/Events.cs
  src/RecyclableMemoryStreamManager.cs
Labels: enhancement

#268 Add tracking for stream lifetime
  UnitTests/Tests.cs
  src/EventArgs.cs
  src/Events.cs
  src/RecyclableMemoryStream.cs
  src/RecyclableMemoryStreamManager.cs
Labels: enhancement

#271 Fix bug. Can't have TimeSpan in event source.
  src/Events.cs
  src/RecyclableMemoryStreamManager.cs
Labels: bug

#273 More optimized remainder calculation
  src/RecyclableMemoryStream.cs
Labels: optimization

#276 Reduce amount of array accesses
  src/RecyclableMemoryStream.cs
Labels: optimization

#278 Override CopyTo to improve performance
  src/RecyclableMemoryStream.cs
Labels: optimization
